spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  server:
    port: 9090
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  doc:
    swagger-ui:
      path: /swagger-ui.html
  jwt:
    token:
      validity: 900
      signing-key: MxtxKNag8gHIYFg8BzdXZWF57bOEDCjSgq3R+u6cfe5LD5oEqvwIhgurwR50haI4UqiBU2l5Gs4ElYy7PT/KRqNL7Pd5yZLgx/W4YI42Bx9ihOJiR1nDRJt7VeYQxpRevzQ2Mi4zfIqKm35HGJxHKTu9noi4m6N6++WjwIuTo7onv5ZdrbV6WoF+U5yRJcKMfoaZoj0jcTh3uct1EFwFokvY2gVWoQdNGxa4FQ==%
    authorities:
      key: roles
      prefix: Bearer
    header:
      string: Authorization
