server:
    port: 9090
    ssl:
      enabled: true
      key-store-type: PKCS12
      key-store: classpath:keystore/baeldung.p12
      key-store-password: fFSF@.421
      key-alias: baeldung

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cardeneta-dev?currentSchema=cardeneta
    username: postgres
    password: fFSF@.421
  server:
    port: 9090
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
    open-in-view: false
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  doc:
    swagger-ui:
      path: /swagger-ui.html
  jwt: # Move all jwt properties under this single declaration
    signing.key: MxtxKNag8gHIYFg8BzdXZWF57bOEDCjSgq3R+u6cfe5LD5oEqvwIhgurwR50haI4UqiBU2l5Gs4ElYy7PT/KRqNL7Pd5yZLgx/W4YI42Bx9ihOJiR1nDRJt7VeYQxpRevzQ2Mi4zfIqKm35HGJxHKTu9noi4m6N6++WjwIuTo7onv5ZdrbV6WoF+U5yRJcKMfoaZoj0jcTh3uct1EFwFokvY2gVWoQdNGxa4FQ==
    token:
      validity: 900
      prefix: Bearer
    authorities:
      key: roles
    header:
      string: Authorization
